import nextEslintPluginNext from '@next/eslint-plugin-next';
import nx from '@nx/eslint-plugin';
import baseConfig from '../../eslint.config.mjs';

export default [
  { plugins: { '@next/next': nextEslintPluginNext } },
  ...nx.configs['flat/react-typescript'],
  ...baseConfig,
  {
    // next-env.d.ts is regenerated by Next.js on every build and its
    // triple-slash reference is required by Next's own convention, not
    // something to hand-fix.
    ignores: ['.next/**/*', 'next-env.d.ts'],
  },
];
