-- AlterEnum
ALTER TYPE "StatutoryRateCode" ADD VALUE 'GHANA_TIER2_PENSION_EMPLOYER';
ALTER TYPE "StatutoryRateCode" ADD VALUE 'KENYA_SHIF_EMPLOYEE';
ALTER TYPE "StatutoryRateCode" ADD VALUE 'KENYA_HOUSING_LEVY_EMPLOYEE';
ALTER TYPE "StatutoryRateCode" ADD VALUE 'KENYA_HOUSING_LEVY_EMPLOYER';

-- AlterTable
ALTER TABLE "payslips" ADD COLUMN "ghana_tier2_pension_employer" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "kenya_shif_employee" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "kenya_housing_levy_employee" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "kenya_housing_levy_employer" DECIMAL(65,30) NOT NULL DEFAULT 0;
